#!/bin/bash
cd ~/mod/mod-plugin-builder/plugins/package
echo "#"'!'"/bin/bash" > ../../compileAllPlugins
for d in *; do
  echo "./build x86_64 $d | tee build$d.log" >> ../../compileAllPlugins
done
cd ~/mod/mod-plugin-builder
chmod 777 compileAllPlugins
