#!/bin/bash
killall mod-ui
killall mod-host
# JACK:
killall jackd

# PW: Change to your audio device. Get this by changing the default sink/input in the ubuntu ui and then then `pactl get-default-sink` and `pactl get-default-source`
#pactl set-default-sink "alsa_output.usb-Yamaha_Corporation_Steinberg_UR22-00.analog-stereo"
#pactl set-default-source "alsa_input.usb-Yamaha_Corporation_Steinberg_UR22-00.analog-stereo"

systemctl --user stop pipewire-pulse.socket pipewire.socket

# JACK:
jackd -R -P 80 -d alsa -d hw:UR22,0 -r 48000 -p 64 -n 2 -X seq &
#jackd -R -P 80 -d alsa -d hw:UR22mkII,0 -r 96000 -p 512 -n 3 -X seq &

sleep 2
# JACK:
pactl load-module module-jack-sink
pactl load-module module-jack-source

# PW: 
#pw-metadata -n settings 0 clock.force-rate 48000
#pw-metadata -n settings 0 clock.min-quantum 256
#pw-metadata -n settings 0 clock.max-quantum 256
#pw-metadata -n settings 0 clock.force-quantum 256

sleep 1

# Copy a working default to the last setting in order to always be able to start MOD even if some recently loaded plugin crashes during load because of an update or else
cp -f ~/mod/mod-ui/data/last.json.default ~/mod/mod-ui/data/last.json 

# MOD-HOST
cd ~/mod/mod-host

./mod-host -v -n -p 5555 -f 5556 &
sleep 1

# MOD-UI
cd ~/mod/mod-ui
virtualenv modui-env
source modui-env/bin/activate

export MOD_DEV_ENVIRONMENT=0
export MOD_USER_FILES_DIR=~/mod/user-files
python3 ./server.py &

sleep 3

firefox http://localhost:8888 &

cd ~
