#!/bin/bash

sudo apt-get update && sudo apt-get upgrade

# As of [here](https://github.com/moddevices/mod-host), [here](https://github.com/moddevices/mod-ui) and [here](https://github.com/moddevices/mod-plugin-builder) install the following:
sudo apt install ubuntustudio-installer git libreadline-dev liblilv-dev lilv-utils libfftw3-dev libjack-jackd2-dev virtualenv \
    python3-pip python3-dev git build-essential libasound2-dev libjack-jackd2-dev liblilv-dev libjpeg-dev \
    zlib1g-dev acl bc curl cvs git mercurial rsync subversion wget bison bzip2 flex gawk gperf gzip help2man \
    nano perl patch tar texinfo unzip automake binutils build-essential cpio libtool libncurses-dev pkg-config \
    python-is-python3 libtool-bin libmtdev-dev libsqlclient-dev libsqlitecpp-dev libpulse-dev libx11-dev \
    libfontconfig1-dev libc++-dev glibc-source linux-libc-dev \
    automake binutils build-essential cpio libtool libncurses-dev pkg-config python-is-python3 \
    libtool-bin libmtdev-dev libsqlclient-dev libpulse-dev libx11-dev libfontconfig1-dev \
    libc++-dev glibc-source linux-libc-dev liblua5.1-0-dev meson mc -y

cd ~
mkdir mod
cd mod
git clone --recurse-submodules https://github.com/moddevices/mod-host.git
git clone --recurse-submodules https://github.com/moddevices/mod-ui.git
git clone --recurse-submodules https://github.com/rominator1983/mod-plugin-builder.git
git clone https://github.com/rominator1983/completeModInstallationManual.git

cd ~/mod/mod-host
make
sudo make install

cd ~/mod/mod-ui
               
# this was sometimes needed to run mod-ui later. This is probably a ubuntu thing
sudo apt-get remove pipenv -y

virtualenv modui-env
source modui-env/bin/activate
pip install pipenv
pip3 install -r requirements.txt

# this is also needed to run mod-ui later
pip install pycryptodomex

pyMinorVersion="$(python3 -c 'import sys; print(sys.version_info[:][1])')"
sed -i -e 's/collections.MutableMapping/collections.abc.MutableMapping/' modui-env/lib/python3."$pyMinorVersion"/site-packages/tornado/httputil.py
make -C utils

echo "Starting bootstrap.sh"
read
cd ~/mod/mod-plugin-builder
# This will take hours on ANY machine
./bootstrap.sh x86_64 > bootstrap.log 2>&1
